//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirstEFconsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Course_id { get; set; }
        public string coursename { get; set; }
        public System.DateTime Startdate { get; set; }
        public int Fees { get; set; }
    }
}
