//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirstEFconsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traineee
    {
        public int TId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string TechDomain { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
