//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_ExaminationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamTable()
        {
            this.SubjectTables = new HashSet<SubjectTable>();
        }
    
        public int ExamId { get; set; }
        public string ExamType { get; set; }
        public int Stdrollno { get; set; }
        public int Tmarks { get; set; }
    
        public virtual StudentTable StudentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectTable> SubjectTables { get; set; }
    }
}
