//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_ExaminationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTable
    {
        public int Stdrollno { get; set; }
        public int ExamId { get; set; }
        public int English { get; set; }
        public int Maths { get; set; }
        public int Science { get; set; }
        public int Social { get; set; }
    
        public virtual ExamTable ExamTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
